# Generated by Django 4.2.4 on 2023-09-01 10:40

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobportal', '0002_jobs_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField()),
                ('cv', models.FileField(upload_to='')),
                ('date_applied', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
