# Generated by Django 4.2.4 on 2023-09-06 07:20

from django.db import migrations, models
import jobportal.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0003_alter_jobs_date_end_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='date_end',
            field=models.DateTimeField(default=jobportal.models.in_five_days),
        ),
    ]
