# Generated by Django 4.2.4 on 2023-09-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0002_alter_item4rent_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item4rent',
            name='status',
        ),
        migrations.AddField(
            model_name='item4rent',
            name='rented',
            field=models.BooleanField(default=False),
        ),
    ]
