# Generated by Django 4.2.4 on 2023-09-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0003_remove_item4rent_status_item4rent_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='item4rent',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
